### ISSUE TITLE
Repair to work with 256 bytes/sector images (ATR really tested)

### ISSUE THREAD

**Issue by pajkduf** [jduerstock/adir#1]
Hello,
i have used this program long time beforehand, on old Linux compilers it worked, but had memory safety errors. So it was some kind of "Anatolij Djatlov mode on :)" ... Today i have found your revised version for modern compilers, but i see, that it is still really not working with atr images with 256 bytes per sector, because of probably older original author's error in cdsk.cpp. Those atr files with double density are quite common in Atari emulator world. I suppose i repaired adir error, but will not create fork or some other things on Github. But (because the original page of Mr. Kubec probably does not work) you can (of course if you want) publish my repair here. Pavel Dufek, Czech Republic, pavel.dufek@tpc.cz. In case of need, please contact me via mail.

Files touched by me attached - really only the code change in cdsk.cpp is needed.
[adir_original_and_repaired_files.zip](https://github.com/jduerstock/adir/files/9723985/adir_original_and_repaired_files.zip)

**Comment by jduerstock** [comment]
Hello!  This bug annoyed me but I never dug deep enough to figure out why it bombed out like it did.  Thank you for finding this and submitting the patch.  It has been integrated into the source tree.
